config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lists#index'
  resources :lists, only: %i[index show create new edit update destroy] do
    resources :bookmarks, only: %i[create new]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add a movie to <%= @list.name %></h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, collection: Movie.order(:title) %>
    <%= f.input :comment %>
    <%= f.submit 'Add movie', class: "btn btn-flat" %>
  <% end %>
  <hr>
    <%= link_to "Go back", list_path(@list)  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <div class="container">
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <div class="container-fluid">
          <%= link_to lists_path, class: "navbar-brand" do %>
            <i class="fa-solid fa-film" style= "font-size: 30px"></i>
            <i class="fa-solid fa-film" style= "font-size: 30px; color: blue"></i>
            <i class="fa-solid fa-film" style= "font-size: 30px"></i>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
              <%# if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to "All Lists", lists_path, class: "nav-link" %>
                <li class="nav-item active">
                  <%= link_to "Create a List", new_list_path, class: "nav-link"%>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <%= yield %>
        <div class="footer">
          <%# <div class="footer-links">
            <a href="#"><i class="fab fa-github"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
          </div> %>
          <div class="footer-copyright">
            Hope you enjoy my first app! <i class="fas fa-heart"></i>
          </div>
        </div>
      </div>
    </body>
  </html>

app/views/lists/index.html.erb
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/10599961/pexels-photo-10599961.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1);">
    <div class="container">
      <h1><strong>Save Movies</strong>, watch whenever...</h1>
    </div>
  </div>
  <hr>
  <div class="cards">
    <% @lists.each do |list| %>
      <% if list.photo.key.blank? %>
        <div class="card-category"style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path("zf9q1tc6vwxy6t1gf0h84q7cokp2", height: 300, crop: :fill) %>')">
        <% else %>
          <div class="card-category"style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
        <% end %>
          <%= link_to list.name, list_path(list), class: "index-link" %>
          <%= link_to list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "card-remove" do %>
            <i class="fa-regular fa-trash-can" ></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Create a New Movie List</h1>
  <%= simple_form_for(@list) do |f|  %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
  <hr>
  <%= link_to "Back to Lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <% if @list.photo.key.blank? %>
    <div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path("zf9q1tc6vwxy6t1gf0h84q7cokp2", height: 300, crop: :fill) %>');">
    <% else %>
      <div class="banner-small" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>');">
      <% end %>
      <div class="container">
        <h1><%= @list.name %></h1>
        <%= link_to list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "banner-remove" do %>
          <i class="fa-regular fa-trash-can" ></i>
        <% end %>
      </div>
    </div>
    <%= link_to "+ Add a movie +", new_list_bookmark_path(@list) %>
    <%= link_to "- Delete This List -", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this WHOLE list?"} %>
    <div style="display: flex; flex-flow: row wrap">
      <% @list.movies.each do |movie| %>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <div class="card" style="width: 36rem; margin: 20px">
          <%= image_tag movie.poster_url %>
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %></h5>
            <h6 class="card-title"><span class="fw-bolder text-muted"><%= movie.rating %></span><i class="fa-solid fa-star" style="color: #FEDE01;"></i></h5>
            <p class="card-text"><%= movie.overview %></p>
            <p class="card-text"><i class="fa-sharp fa-solid fa-quote-left me-1"></i></i><strong><%= bookmark.comment%></strong></p>
            <%= link_to "Remove from list", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-secondary"%>
          </div>
        </div>
      <% end %>
    </div>
    <hr>
    <%= link_to "Back to Lists", lists_path %>